import { ElementRef,
    Renderer2, EventEmitter, ComponentFactoryResolver, KeyValueDiffers, OnInit, OnDestroy, DoCheck, ViewContainerRef } from '@angular/core';
import { INgWidgetEvent, INgWidgetPosition, INgWidgetSize, INgWidgetContainerConfig } from "../interfaces/INgDraggableWidgetConfig";
import { NgWidget } from './NgWidget';
export declare class NgWidgetContainer implements OnInit, DoCheck, OnDestroy {
    private _differs;
    private _ngEl;
    private _renderer;
    private componentFactoryResolver;
    private _containerRef;
    private static CONST_DEFAULT_CONFIG;
    onDragStart: EventEmitter<NgWidget>;
    onDrag: EventEmitter<NgWidget>;
    onDragStop: EventEmitter<NgWidget>;
    onResizeStart: EventEmitter<NgWidget>;
    onResize: EventEmitter<NgWidget>;
    onResizeStop: EventEmitter<NgWidget>;
    onItemChange: EventEmitter<Array<INgWidgetEvent>>;
    colWidth: number;
    rowHeight: number;
    minCols: number;
    minRows: number;
    marginTop: number;
    marginRight: number;
    marginBottom: number;
    marginLeft: number;
    isDragging: boolean;
    isResizing: boolean;
    autoStyle: boolean;
    resizeEnable: boolean;
    dragEnable: boolean;
    cascade: string;
    minWidth: number;
    minHeight: number;
    zIndex: number;
    allowOverlap: boolean;
    widget_width_factor: number;
    widget_height_factor: number;
    private _items;
    private _draggingItem;
    private _resizingItem;
    private _resizeDirection;
    private _itemGrid;
    private _containerWidth;
    private _containerHeight;
    private _maxCols;
    private _maxRows;
    private _visibleCols;
    private _visibleRows;
    private _setWidth;
    private _setHeight;
    private _posOffset;
    private _adding;
    private _placeholderRef;
    private _fixToGrid;
    private _autoResize;
    private _differ;
    private _destroyed;
    private _maintainRatio;
    private _aspectRatio;
    private _preferNew;
    private _zoomOnDrag;
    private _limitToScreen;
    private _curMaxRow;
    private _curMaxCol;
    private _dragReady;
    private _resizeReady;
    private _config;
    config: INgWidgetContainerConfig;
    constructor(_differs: KeyValueDiffers, _ngEl: ElementRef, _renderer: Renderer2, componentFactoryResolver: ComponentFactoryResolver, _containerRef: ViewContainerRef);
    ngOnInit(): void;
    ngOnDestroy(): void;
    getConfig(): INgWidgetContainerConfig;
    setConfig(config: INgWidgetContainerConfig): void;
    getItemPosition(index: number): INgWidgetPosition;
    getItemSize(index: number): INgWidgetSize;
    ngDoCheck(): boolean;
    setMargins(margins: Array<string>): void;
    enableDrag(): void;
    disableDrag(): void;
    enableResize(): void;
    disableResize(): void;
    addItem(ngItem: NgWidget): void;
    removeItem(ngItem: NgWidget): void;
    updateItem(ngWidget: NgWidget): void;
    triggerCascade(): void;
    triggerResize(): void;
    resizeEventHandler(e: any): void;
    mouseDownEventHandler(e: MouseEvent): void;
    mouseUpEventHandler(e: any): void;
    mouseMoveEventHandler(e: any): void;
    private updatePositionsAfterMaxChange();
    private _calculateColWidth();
    private _calculateRowHeight();
    private _updateRatio();
    private _applyChanges(changes);
    private _resizeStart(e);
    private _dragStart(e);
    private _zoomOut();
    private _resetZoom();
    private _drag(e);
    private _resize(e);
    private _dragStop(e);
    private _resizeStop(e);
    private _maxGridSize(w, h);
    private _calculateGridSize(width, height);
    private _calculateGridPosition(left, top);
    private _hasGridCollision(pos, dims);
    private _getCollisions(pos, dims);
    private _fixGridCollisions(pos, dims);
    private _cascadeGrid(pos?, dims?);
    private _cascadePlaceHolder(pos?, dims?);
    private _fixGridPosition(pos, dims);
    private _isWithinBoundsX(pos, dims);
    private _fixPosToBoundsX(pos, dims);
    private _fixSizeToBoundsX(pos, dims);
    private _isWithinBoundsY(pos, dims);
    private _fixPosToBoundsY(pos, dims);
    private _fixSizeToBoundsY(pos, dims);
    private _isWithinBounds(pos, dims);
    private _fixPosToBounds(pos, dims);
    private _fixSizeToBounds(pos, dims);
    private _addToGrid(item);
    private _removeFromGrid(item);
    private _filterGrid();
    private _updateSize();
    private _getMaxRow();
    private _getMaxCol();
    private _getMousePosition(e);
    private _getAbsoluteMousePosition(e);
    private _getContainerColumns();
    private _getContainerRows();
    private _getItemFromPosition(position);
    private _createPlaceholder(item);
    private _emitOnItemChange();
}
